name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el código fuente del repositorio
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Paso 2: Instalar Node.js y NPM
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Usa la versión adecuada de Node.js para Angular

      # Paso 3: Instalar dependencias de NPM
      - name: Install dependencies
        run: |
          npm install

      # Paso 4: Ejecutar pruebas
     # - name: Run tests
      #  run: npm test

      # Paso 5: Construir la aplicación Angular
      - name: Build Angular project
        run: npm run build --prod

      # Paso 6: Obtener la versión de la aplicación desde package.json
      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      # Paso 7: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 8: Configurar caché de Docker
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Paso 9: Iniciar sesión en Docker Hub
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

      # Paso 10: Construir la imagen Docker
      - name: Build and Tag Docker Image
        run: |
          docker buildx build \
            -t alorpes/deepdiverecord-web:${{ env.VERSION }} \
            -t alorpes/deepdiverecord-web:latest \
            --push .
